version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fastapi-network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: bennett-server:latest
    container_name: fastapi_app
    environment:
      DATABASE_URL: mysql+mysqlconnector://fastapi_user:your_password@db:3306/fastapi_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - fastapi-network

volumes:
  db_data:

networks:
  fastapi-network: