apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: fastapi
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
  replicas: 1
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: bennett-server:latest
          imagePullPolicy: Never # local image 사용
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "mysql+mysqlconnector://fastapi_user:your_password@mysql:3306/fastapi_db"