name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up GCP credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker auth
        run: |-
          gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
#
#
#      - name: Log in to GCR
#        run: echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform=linux/amd64,linux/arm64 \
          --push \
          --tag gcr.io/socar-data-dev/onboarding-bennett:latest .

      - name: Remove buildx builder
        run: docker buildx rm